[package]
name = "res_slin"
version = "0.1.0"
edition = "2021"
authors = ["Abe <sealfinish@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
